# This Dockerfile provides a minimal usage example for a consumer to benefit
# from the Apt-Cacher NG service provided by the project

# To build run the following:
#    1. make up
#    2. DOCKER_CONFIG=. docker build --network host --file Dockerfile.apt_cacher_ng_consumer_recommended .

FROM ubuntu:20.04 as apt_cacher_ng_consumer_recommended


RUN apt-get update && apt-get install -y curl


RUN apt-get update && apt-get install -y cowsay
RUN /usr/games/cowsay "Hello, Apt-Cacher NG! Consumer Recommended"



